# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Frame Test Suite

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
        
    - name: Current Directory name
    - run: pwd
    
    - name: Go to /framec
    - run: cd ./framec
    
    - name: Rust version
    - run: rustc --version
    
    - name: Build
    - run: cargo build --release
