# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Frame Test Suite

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone frame_transpiler
      uses: actions/checkout@v2
      with:
        repository: frame-lang/frame_transpiler
        path: './frame_transpiler'
        
    - name: Clone framepiler_tests
      uses: actions/checkout@v2
      with:
        repository: frame-lang/framepiler_tests
        path: './framepiler_tests'

    - name: Build frame_transpiler
      working-directory: ./frame_transpiler/framec
      run: cargo build --release
      
    - name: Copy framec to test suite
      run: cp ./frame_transpiler/target/release/framec ./framepiler_tests
    
    - name: Setup Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x

    - name: Install dependencies
      working-directory: ./framepiler_tests
      run: npm install
      
    - name: Setup .env file and create temp folder
      working-directory: ./framepiler_tests
      run: |
        cp .env.sample .env
        chmod +x update_env.sh
        ./update_env.sh ${{ secrets.MAIL_FROM }} ${{ secrets.MAIL_TO }} ${{ secrets.MAILGUN_API_KEY }} ${{ secrets.MAILGUN_DOMAIN }}
        mkdir temp
  
    - name: Run the Test Suite
      working-directory: ./framepiler_tests
      run: npm run prod
