# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Frame Test Suite

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone transpiler_copy
      uses: actions/checkout@v2
      with:
        repository: gaurav-ongraph/transpiler_copy
        path: './transpiler_copy'
        
    - name: Clone framepiler_tests
      uses: actions/checkout@v2
      with:
        repository: frame-lang/framepiler_tests
        path: './framepiler_tests'
        
    - name: Current Directory name
      run: pwd
    
    - name: Build the transpiler
      working-directory: ./transpiler_copy/framec
      run:  |
        pwd
        rustc --version
        cargo build --release
        
    
    - name: Current Directory name
      run: pwd
  
    #- name: Build
    #  run: cargo build --release
      
#     - name: Go to root
#       run: cd
    
#     - name: Current Directory name
#       run: pwd
      
#     - name: Clone test repo
#       run: git clone https://github.com/frame-lang/framepiler_tests.git
    
    - name: Setup Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
