# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Frame Test Suite

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone transpiler_copy
      uses: actions/checkout@v2
      with:
        repository: gaurav-ongraph/transpiler_copy
        path: './transpiler_copy'
        
    - name: Clone framepiler_tests
      uses: actions/checkout@v2
      with:
        repository: frame-lang/framepiler_tests
        path: './framepiler_tests'

    - name: Build the transpiler
      working-directory: ./transpiler_copy/framec
      run: cargo build --release
      
    - name: Copy framec to test suite
      run: cp ./transpiler_copy/target/release/framec ./framepiler_tests
    
    - name: Setup Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
      
#     - name: Copy env file
#       working-directory: ./framepiler_tests
#       run: cp .env.sample .env

    - name: Install dependencies
      working-directory: ./framepiler_tests
      run: |
        pwd
        node -v
        npm install
      
    - name: Run the Test Suite
      working-directory: ./framepiler_tests
      run: npm run prod
