# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Frame Test Suite

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone transpiler_copy
      uses: actions/checkout@v2
      with:
        repository: gaurav-ongraph/transpiler_copy
        path: './transpiler_copy'
        
    - name: Clone framepiler_tests
      uses: actions/checkout@v2
      with:
        repository: frame-lang/framepiler_tests
        path: './framepiler_tests'
        
    - name: Current Directory name
      run: pwd
    
    - name: Build the transpiler
      working-directory: ./transpiler_copy/framec
      run:  |
        pwd
        rustc --version
        cargo build --release
        
    
    - name: Current Directory name
      run: pwd
    
    - name: Setup Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        
    - name: node version
      run: node -v
      
    - name: Copy env file
      working-directory: ./framepiler_tests
      run: |
        pwd
        cp .env.sample .env
        echo "$HOME"
      
    - name: Check frmaec 1
      working-directory: ./framepiler_tests
      run: ls -t

    - name: Copy framec to test suite
      run: cp .transpiler_copy/target/release/framec /home/runner/work/framepiler_tests
      
    - name: Check frmaec 2
      working-directory: ./framepiler_tests
      run: ls -t
